name: Terraform Test

on:
  pull_request:
    paths:
      - 'Terraform_aws/Terraform_code/**'
      - 'Terraform_aws/Terraform_code/**/*.tftest.hcl'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

  push:
    branches:
      - main
    paths:
      - 'Terraform_aws/Terraform_code/**'
      - 'Terraform_aws/Terraform_code/**/*.tftest.hcl'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

jobs:
  Terraform_test_jobs:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1

    defaults:
      run:
        working-directory: Terraform_aws/Terraform_code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Test
        run: terraform test