- name: Javaのインストール/Springboot起動
  hosts: web
  become: true

  tasks:
    - name: EC2接続確認
      ansible.builtin.ping:
      register: ping_result

    - name: 接続確認結果を表示
      ansible.builtin.debug:
        var: ping_result

    - name: Java 21 をインストール
      ansible.builtin.dnf:
        name: java-21-amazon-corretto-devel
        state: present 

    - name: Java バージョンコマンド
      ansible.builtin.command: java -version
      register: java_version
      changed_when: false

    - name: Java バージョン確認
      ansible.builtin.debug:
        msg: "{{ java_version.stderr_lines[0] }}"

    - name: git をインストール
      ansible.builtin.dnf:
        name: git
        state: present
    
    - name: git バージョンコマンド
      ansible.builtin.command: git --version
      register: git_version
      changed_when: false

    - name: git バージョン確認
      ansible.builtin.debug:
        var: git_version

    - name: git clone
      ansible.builtin.git:
       repo: https://github.com/koujienami/aws-study.git
       dest: /home/ec2-user/aws-study
       force: true
      register: git_clone_result 

    - name: git clone 結果を表示
      ansible.builtin.debug:
        var: git_clone_result

    - name: gradlew 実行権限 755 
      ansible.builtin.command: chmod 755 gradlew
      args:
        chdir: /home/ec2-user/aws-study
        
    - name: spring boot run
      ansible.builtin.command: ./gradlew bootRun
      args:
        chdir: /home/ec2-user/aws-study
      register: bootRun_result
      async: 300
      poll: 0
      
    - name: Springboot起動結果を表示
      ansible.builtin.debug:
        var: bootRun_result
