name: Terraform Test

on:
 pull_request:
   paths:
      - 'Terraform_aws/Terraform_code/**'
      - 'Terraform_aws/Terraform_code/**/*.tftest.hcl'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

 push:
   branches: 
   - master
   - Terraform

jobs:
  Terraform_test_jobs:
    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: Terraform_aws/Terraform_code
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init 
      run:  terraform init

    - name: Terraform validate
      run:  terraform validate
    
    - name: Terraform  Test
      run:  terraform test
   